apiVersion : apps/v1
kind: Deployment
metadata:
  name: "shopwarek8sdevcluster-0d31"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "shopwarek8sdevcluster-0d31"
  template:
    metadata:
      labels:
        app: "shopwarek8sdevcluster-0d31"
    spec:
      containers:
        - name: "shopwarek8sdevcluster-0d31"
          image: "shopwarek8sdev.azurecr.io/shopwarek8sdevcluster"
          ports:
          - containerPort: 80